name: annotations
description: Annotations for generators.
version: 1.0.0
author: Aachman Garg <imaachman@gmail.com>
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
dev_dependencies:
  test: 1.3.4
